baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Richard Chin'
metaDataFormat = "yaml"
sectionPagesMenu = "main"
summarylength = 15

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
    description = "Product marketing leader, entrepreneur and YouTube content creator."
    images = ["sondurenfanarredha-og.jpg"]
    logoSchema = "/uploads/logo-sondurenfanarredha.png"
    googleTagManagerID = "GTM-xxxxxx"
    linkedin = "chinrichard"
    youtube = "ricch13"
    instagram = "ricch13"
    github = "ricch"