baseURL = 'https://richard-chin.netlify.app/'
languageCode = 'en-us'
title = 'Richard Chin'
metaDataFormat = "yaml"
sectionPagesMenu = "main"
summarylength = 15

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
    description = "Web Developer focusing on high growth strategies for B2B Saas companies"
    images = ["og-richardchin.jpg"]
    logoSchema = "/uploads/schema-richardchin.png"
    googleTagManagerID = "GTM-xxxxxx"
    linkedin = "chinrichard"
    youtube = "ricch13"
    instagram = "ricch13"
    github = "ricch"